spring:
  data:
    neo4j:
      repositories:
        type: IMPERATIVE
      database: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

hop-weight: 0.9

