spring:
  application:
    name: Skill Endorsement Relevance System
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db.migration

server:
  port: ${PORT:8080}